[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
lib_ldf_mode = chain

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I/Users/colonelpanic/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/esp_wifi/include
    -I/Users/colonelpanic/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/esp_netif/include
    -I/Users/colonelpanic/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/esp_event/include

lib_deps =
  bblanchon/ArduinoJson@^6.20.0